language: objective-c
osx_image: xcode11.5
env:
  global:
  - APP_NAME="DemoCi"
  - 'DEVELOPER_NAME="iPhone Distribution: 波波 裴(49YDWUASFN)"'
  - PROFILE_NAME="TravisCIADHoc"
  - secure: FV+z1GyfKry4IPFefjrC5otsh+f/pRlWn1u1aPeXexfGCbD91zAnDZKV3kUbxtsth/3mf8qH5DBKSKVe9Xcccde/IjorMYgW7e0GblK0htv9OI6kqvZZslKPrq1mAFySAUatWw6S7UEC0eZPmND+3yZU80jjMTIL8NWS/cGKOkMel9H7U9sLGEajyX5JXlS6P0DRD//qxJayFaGJFS2zS0FhnEg475IzJdvs73Z1ZT/7Sa5YBMKYzzjzWt2/u90QhFCJ7yZsQ1lCpeVbYmik1hH10XwHhMSywg1d0Y+mOQya412s60IN9z1L412hwMCSMEWf7rRncxYwR9CRwYMTcAazz3QUUKMsRReyIiLjV9D8qCzXaBMoYWLXc9L+V9K7j0sKKKGJcb35IG6xX20Z8VqxTzDK+XX3Fy+QFHRgVolWvkW/ARrXrdLrDpKnEKz2m6EcbmeA6YUvIX+GTvJpV0/2nHWFcbWB5uU0oUygNNOJq23JqfhNTwzNunrIYuweRYSjREbfUHH/f+SVd1Plz+yxdHJe1Fh2bqgR1i9ZlQDsCf2QdUlIEYJiD1FfeyUjjO1UsyEFXjIpTs2kgPbmvtgn1A1jFvdinZYxK3R7h9qrumBMKSqelOrRQA2vvWWG7sOMb5iq+nGZhQmRYE/+qZn+ehjbhsh9IXmehG6CSNA=
  - secure: fXfVXYjz2EXpgrz9n+43vK1nWcM9p/5Gk3vgyTVBQ/onJ7Q68bH7m8JFQGWbFpCocbtMd10pFWvo4EwCQI9kGQ7n/eYItzkQWDRk0y+8cVG7SMCWAOgjMxC0ZxyrzFv6msLDzbtuxUZ4/veYcYDH9oP3sABlb7jxrdLi+QB8cbHbqYK1Tcm64S5TFMvIBdNveIZR5yDrmi7bZfddKp0hYwqTP59MB6w8xkfvEmZTq+AZPm5JYo5FNW6+L5cg3vvM85PiOunrGp2QVb9uhRHJgFI4e+u97/DEmkcdJva7rjt7dA3fA5WSISlBwghGcvfts/XbTUEAVhAeENgIAZrloSnhF3EM2jb3phTPC4Neag2ErNXTHsopSyTSTcobgIN5NM2Z8eIWKj/brBmwG9YQq0vjXRUh0sXEp16bnWpQVn4aOUMJWQhyaAIhSKWosUG3w9lqh+Xv+jfWfli4YO5+jOf/n/ShJgp9LBrweLoigkuNz1xu1zhNC9pIEvH/xl9RKalkYEf2xtlvBb92W8U9MBsp6utwxD4kCHTrwsiET01FCi8EqPdMeFwoFoChdcf2B2/v0k3+bht6VX7D2q3aXJfOaud+RipjEnzZ613arB35mUHqlBSprF8h2QSGrRdKyOZanUVaH/LdoQ+29BAXBEMRxu0W9UlHIeCW1f9+q1A=
before_install:
- cd scripts/
- wget -c https://raw.githubusercontent.com/Pgyer/TravisFile/master/pgyer_upload.sh
  -O pgyer_upload.sh
- chmod +x pgyer_upload.sh
- chmod +x add-key.sh
- chmod +x upload.sh
- chmod +x remove-key.sh
- chmod +x build.sh
- cd ..
before_script:
- "./scripts/add-key.sh"
script:
- "./scripts/build.sh"
after_success:
- "./scripts/remove-key.sh"

#- "./scripts/upload.sh"
#after_script:
#- "./scripts/remove-key.sh"
