language: objective-c
osx_image: xcode11.5
script:
- xctool -workspace $DemoCi.xcworkspace -scheme $DemoCi -sdk iphoneos  -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="$DEVELOPER_NAME"
