language: objective-c
osx_image: xcode11.5
env:
  global:
  - APP_NAME="DemoCi"
  - 'DEVELOPER_NAME="iPhone Distribution: Bobo Pei(49YDWUASFN)"'
  - PROFILE_NAME="TravisCIADHoc"
  - secure: o+QjjwHoa0HRQNNRYvXAjbZlPTeVwuRtff+sfj2YelG61LfvCHlAjUs4K7ex7F1LCXLUtaYRawsnMpBL5IY2iLATCsGoqyhYcQut49+n6uduFYTPVNiANierSSlBmgfv+KVZ8uHQXeMfFN47U2Gm4B6qU8qMAr9FvlW9y2OdHPggkrhEl7rDBBv+d7XxgZ+mHdWBbI2GOveFp+11AFm8Z68UW7KVVGX+1qypx3DAfcX/kJKVDJivP9NBuUYjunqXrf+ASj1FaNVcqHvy8cr+NA2nB3Io0/6diqcV/WgY1yiwNHetRM0pzQp5xHZ1GHVsdSMK7jLzrD4ad+y5NbHsU+kkqKpNxoBZi0PNgPYg+xAMNcOoOY6p8Z/XJBZ6idy+vt3gib00/V0lpkrwxxrgzF2+PygfmfoWiCWXvrl9cxwhO2+zbP+Zg4UVXFiSCqZ+3/hrUYCmZOo2dLyhnqAYry0gPnS1lPQ6TBBGCE6AFVdl6CrqWmoZmZfVNk1LvGB55enmX7carTYlCiq/50fG6cms1dW0abPYR9rQno91Gfih0O+TQog+AeajDj+YcNffoYDdMJxKh/VyKAumkbprhmXTTzUbWZHLJUidjrrz82/gSULfywtJKF8ixFaIYt1eHIup7tdUnNmJyi7/YkrW6CDyLtn6gV4DXTek5YcKUqQ=
  - secure: ScqEZC95tRivQP2rDSbvlPdwD43tLCKJ6sI1BexhB5yKyIg2FXzU+2cleWXv5PC0Gmw0gQVodQz1WwsiVCkXGy8DulAVfIbIfwKc15RRKieBdUpeoPzz2S8VkCKqWIafY70ZEEJfvgJTWKcygf9nMsxvNIoPdWZ3Ue/Uxf3asdBQBEpSMSvJ1iczIhEMHT185T78VyWEjoAHalbETQHvzu3CT1LK/riUTxGUaTmDLRlbskIr5cuUDclvnx3GwgLpPvXhg79I8ADrD73itzVQuEWgL9hlzrAnHHSyTfE6iueEj7FLpnW8W6GnVlkFcZ0OcM0srJoJFyrrk/yDgxq2hKlb3VAW2lHFf9ZbzdR0p3oRc9V6+T26443kqdGFLBhw9gwB9hCDcdlunOl8Y2Xe7Cikv2Fuqz7/2cqKRxCp7ioBdl4agvefxftkZSSIJKshJhaV7nDFj8oCbIGvSuXITm+exIq4MvcfkfUuJnyz9g5RbjzIyYTiV3UWBqPodMNxkrWhKdXtIxaATz3mzM3XnwAvQollFsDK8c+Mb06RXMKpD5JDkVlQabQu1EAzqBirpMfp/ZIwHw4rfc2c3s38XkIkvA+9n/iAcTupcO0UQ8F2wF+XqdyqiBNLO3XjpqtkuOQKI+kwPQV9wBd5K85pE3wqqb9dPSw8Mxj02/AnzL8=
before_install:
- cd scripts/
- wget -c https://raw.githubusercontent.com/Pgyer/TravisFile/master/pgyer_upload.sh
  -O pgyer_upload.sh
- chmod +x pgyer_upload.sh
- chmod +x add-key.sh
- chmod +x upload.sh
- chmod +x remove-key.sh
- chmod +x build.sh
- cd ..
before_script:
- "./scripts/add-key.sh"
script:
- "./scripts/build.sh"
after_success:
- "./scripts/upload.sh"
after_script:
- "./scripts/remove-key.sh"
